"""Tests for the tool classifier module."""

from __future__ import annotations

import unittest

from deepfake_lens.classifier import (
    ClassificationResult,
    ToolMatch,
    classify_metadata,
    classify_text_content,
    classify_spectral_profile,
    list_all_tools,
    get_tool_info,
)


class ClassifierTest(unittest.TestCase):
    """Test cases for classifier functions."""

    def test_classify_metadata_returns_result(self) -> None:
        """classify_metadata should return a ClassificationResult."""
        result = classify_metadata({"Software": "DALL-E 3"})
        self.assertIsInstance(result, ClassificationResult)

    def test_classify_text_content_returns_result(self) -> None:
        """classify_text_content should return a ClassificationResult."""
        result = classify_text_content("This image was generated by Midjourney v6")
        self.assertIsInstance(result, ClassificationResult)

    def test_classify_spectral_profile_returns_result(self) -> None:
        """classify_spectral_profile should return a ClassificationResult."""
        result = classify_spectral_profile({"spectral_flatness": 0.8})
        self.assertIsInstance(result, ClassificationResult)

    def test_dalle_detection(self) -> None:
        """DALL-E should be detected in metadata."""
        result = classify_metadata({"Software": "DALL-E 3"})
        self.assertGreater(len(result.matches), 0)
        self.assertEqual(result.category, "image")

    def test_midjourney_detection(self) -> None:
        """Midjourney should be detected in text."""
        result = classify_text_content("This image was created with Midjourney")
        self.assertGreater(len(result.matches), 0)
        self.assertEqual(result.category, "image")

    def test_stable_diffusion_detection(self) -> None:
        """Stable Diffusion should be detected."""
        result = classify_text_content("Generated using Stable Diffusion XL")
        self.assertGreater(len(result.matches), 0)

    def test_suno_detection(self) -> None:
        """Suno should be detected."""
        result = classify_text_content("This song was created with Suno v5")
        self.assertGreater(len(result.matches), 0)
        self.assertEqual(result.category, "audio")

    def test_veo_detection(self) -> None:
        """Veo should be detected."""
        result = classify_text_content("Video generated by Google Veo 3")
        self.assertGreater(len(result.matches), 0)
        self.assertEqual(result.category, "video")

    def test_no_match_returns_empty(self) -> None:
        """Text with no markers should return empty matches."""
        result = classify_text_content("This is a normal text with no AI markers")
        self.assertEqual(len(result.matches), 0)
        self.assertIsNone(result.primary_match)
        self.assertEqual(result.category, "unknown")

    def test_primary_match_is_highest_confidence(self) -> None:
        """Primary match should be the highest confidence match or text override."""
        result = classify_text_content("Created with DALL-E 3 by OpenAI")
        if result.primary_match:
            # Primary should be either the highest confidence or a text match with equal/higher confidence
            self.assertTrue(
                result.primary_match == result.matches[0] or
                (result.primary_match.category == "text" and result.primary_match.confidence >= result.matches[0].confidence)
            )

    def test_list_all_tools(self) -> None:
        """list_all_tools should return all categories."""
        tools = list_all_tools()
        self.assertIn("image", tools)
        self.assertIn("video", tools)
        self.assertIn("audio", tools)
        self.assertIn("detection", tools)

    def test_get_tool_info(self) -> None:
        """get_tool_info should return tool information."""
        info = get_tool_info("DALL-E 3")
        self.assertIsNotNone(info)
        self.assertEqual(info["name"], "DALL-E 3")
        self.assertEqual(info["provider"], "OpenAI")

    def test_get_tool_info_not_found(self) -> None:
        """get_tool_info should return None for unknown tool."""
        info = get_tool_info("UnknownTool")
        self.assertIsNone(info)

    def test_tool_match_to_json(self) -> None:
        """ToolMatch to_json should return a dictionary."""
        match = ToolMatch(
            name="Test",
            provider="TestProvider",
            category="test",
            confidence=0.9,
            evidence=["test evidence"],
        )
        data = match.to_json()
        self.assertIsInstance(data, dict)
        self.assertEqual(data["name"], "Test")

    def test_classification_result_to_json(self) -> None:
        """ClassificationResult to_json should return a dictionary."""
        result = classify_text_content("Test text")
        data = result.to_json()
        self.assertIsInstance(data, dict)
        self.assertIn("matches", data)
        self.assertIn("category", data)
        self.assertIn("confidence", data)


if __name__ == "__main__":
    unittest.main()
