"""AI agent detection module.

Detects content generated by autonomous AI agents,
agentic workflows, and automated content creation systems.
"""

from __future__ import annotations

import re
from dataclasses import asdict, dataclass


@dataclass(frozen=True)
class AgentEvidenceSignal:
    title: str
    detail: str
    weight: int


@dataclass(frozen=True)
class AgentAnalysis:
    score: int
    band: str
    band_label: str
    verdict: str
    signals: list[AgentEvidenceSignal]
    limitations: list[str]
    agent_type: str
    confidence: str

    def to_json(self) -> dict[str, object]:
        return asdict(self)


# AI agent markers
AGENT_MARKERS = {
    "openai_agent": ["openai agent", "gpt agent", "chatgpt agent", "operator", "openai operators"],
    "anthropic_agent": ["claude agent", "anthropic agent", "computer use", "claude computer"],
    "google_agent": ["gemini agent", "google agent", "project astra", "google ai studio agent"],
    "microsoft_agent": ["copilot agent", "microsoft agent", "autogen", "semantic kernel"],
    "meta_agent": ["llama agent", "meta agent", "meta ai agent"],
    "langchain": ["langchain", "langgraph", "langsmith", "langchain agent"],
    "crewai": ["crewai", "crew ai", "crewai agent"],
    "autogen": ["autogen", "auto-gen", "pyautogen"],
    "babyagi": ["babyagi", "baby agi"],
    "auto_gpt": ["auto-gpt", "autogpt", "auto gpt"],
    "devin": ["devin", "cognition ai", "devin agent"],
    "sweep": ["sweep ai", "sweep.dev"],
    "cursor_agent": ["cursor agent", "cursor ai", "cursor copilot"],
    "replit_agent": ["replit agent", "replit ai", "replit agent"],
    "openai_swarm": ["openai swarm", "swarm agent"],
    "llamaindex": ["llamaindex", "llama index", "gpt index"],
    "haystack": ["haystack", "deepset"],
    "semantic_kernel": ["semantic kernel", "microsoft semantic"],
    "dspy": ["dspy", "dspy ai"],
    "agentverse": ["agentverse", "agent verse"],
    "metagpt": ["metagpt", "meta gpt"],
}


def analyze_agent_content(
    text: str | None = None,
    metadata: dict[str, str] | None = None,
) -> AgentAnalysis:
    """Analyze content for AI agent generation signs."""
    signals: list[AgentEvidenceSignal] = []
    limitations: list[str] = []
    
    if text:
        text_signals = _analyze_text_for_agents(text)
        signals.extend(text_signals)
    
    if metadata:
        metadata_signals = _analyze_metadata_for_agents(metadata)
        signals.extend(metadata_signals)
    
    # Limitations
    if not text and not metadata:
        limitations.append("텍스트 또는 메타데이터가 제공되지 않았습니다.")
    limitations.append("AI 에이전트 탐지는 아직 초기 단계이며, 오탐율이 높을 수 있습니다.")
    
    score = min(100, sum(signal.weight for signal in signals))
    
    if score >= 67:
        band = "high"
        band_label = "높음"
        verdict = "AI 에이전트에 의해 생성되었을 가능성이 높습니다."
    elif score >= 35:
        band = "medium"
        band_label = "주의"
        verdict = "AI 에이전트 생성 가능성이 일부 감지됩니다."
    else:
        band = "low"
        band_label = "낮음"
        verdict = "AI 에이전트 생성 신호가 거의 없습니다."
    
    agent_type = _classify_agent_type(signals)
    confidence = _calculate_confidence(score, len(signals))
    
    return AgentAnalysis(
        score=score,
        band=band,
        band_label=band_label,
        verdict=verdict,
        signals=signals,
        limitations=limitations,
        agent_type=agent_type,
        confidence=confidence,
    )


def _analyze_text_for_agents(text: str) -> list[AgentEvidenceSignal]:
    """Analyze text for AI agent markers."""
    signals = []
    normalized = text.lower()
    
    for agent_name, markers in AGENT_MARKERS.items():
        for marker in markers:
            if marker.lower() in normalized:
                signals.append(AgentEvidenceSignal(
                    f"{agent_name} 마커 발견",
                    f"'{marker}' 텍스트가 감지되었습니다.",
                    30,
                ))
                break
    
    # Agentic workflow patterns
    workflow_patterns = [
        (r" step \d+[:.]", "단계별 워크플로우 패턴"),
        (r" task \d+[:.]", "작업 기반 워크플로우 패턴"),
        (r" agent[:.]", "에이전트 참조 패턴"),
        (r" tool[:.]", "도구 사용 패턴"),
        (r" action[:.]", "작업 실행 패턴"),
        (r" observation[:.]", "관찰 결과 패턴"),
        (r" thought[:.]", "사고 과정 패턴"),
        (r" executing", "실행 중 패턴"),
        (r" processing", "처리 중 패턴"),
        (r" analyzing", "분석 중 패턴"),
        (r" generating", "생성 중 패턴"),
        (r" completed", "완료 패턴"),
        (r" finished", "완료 패턴"),
        (r" done", "완료 패턴"),
        (r" workflow", "워크플로우 패턴"),
        (r" pipeline", "파이프라인 패턴"),
        (r" automation", "자동화 패턴"),
        (r" automated", "자동화 패턴"),
    ]
    
    for pattern, description in workflow_patterns:
        if re.search(pattern, normalized):
            signals.append(AgentEvidenceSignal(
                "에이전트 워크플로우 패턴",
                f"{description}이 감지되었습니다.",
                20,
            ))
    
    # Automated response patterns
    auto_patterns = [
        (r"i (?:have|will|can) (?:now|automatically|programmatically)", "자동화된 응답 패턴"),
        (r"executing (?:task|command|action)", "작업 실행 패턴"),
        (r"completed (?:task|step|action)", "작업 완료 패턴"),
        (r"running (?:script|code|program)", "스크립트 실행 패턴"),
    ]
    
    for pattern, description in auto_patterns:
        if re.search(pattern, normalized):
            signals.append(AgentEvidenceSignal(
                "자동화 응답 패턴",
                f"{description}이 감지되었습니다.",
                15,
            ))
    
    return signals


def _analyze_metadata_for_agents(metadata: dict[str, str]) -> list[AgentEvidenceSignal]:
    """Analyze metadata for AI agent markers."""
    signals = []
    
    # Check for agent-related metadata
    agent_metadata_keys = [
        "agent", "workflow", "pipeline", "automation",
        "tool", "framework", "orchestrator",
    ]
    
    for key, value in metadata.items():
        key_lower = key.lower()
        value_lower = value.lower() if isinstance(value, str) else ""
        
        for agent_key in agent_metadata_keys:
            if agent_key in key_lower or agent_key in value_lower:
                signals.append(AgentEvidenceSignal(
                    "에이전트 메타데이터",
                    f"메타데이터 키/값에 '{agent_key}'가 포함되어 있습니다.",
                    15,
                ))
                break
    
    return signals


def _classify_agent_type(signals: list[AgentEvidenceSignal]) -> str:
    """Classify the type of AI agent."""
    signal_titles = {s.title for s in signals}
    
    if any("openai" in title.lower() for title in signal_titles):
        return "openai_agent"
    if any("anthropic" in title.lower() for title in signal_titles):
        return "anthropic_agent"
    if any("google" in title.lower() for title in signal_titles):
        return "google_agent"
    if any("microsoft" in title.lower() for title in signal_titles):
        return "microsoft_agent"
    if any("langchain" in title.lower() or "crewai" in title.lower() for title in signal_titles):
        return "framework_agent"
    if any("workflow" in title.lower() or "automation" in title.lower() for title in signal_titles):
        return "agentic_workflow"
    
    return "unknown"


def _calculate_confidence(score: int, signal_count: int) -> str:
    """Calculate confidence level."""
    if score >= 67 and signal_count >= 3:
        return "high"
    if score >= 35 and signal_count >= 1:
        return "medium"
    return "low"
